spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weather
    username: root
    password: nicopoiduang
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: mysql
server:
  port: 80
